site_name: Minormous Framework
theme: 'readthedocs'
pages:
- Framework: index.md
- Authentication: auth.md
- Data: data.md
- Commands: commands.md
- Session: session.md
- Structure: structure.md
- Packages: directory.md
